
version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: DockerWorkshop
  frontend:
    image: philter87/frontend-radar
    ports:
      - 9502:80
  backend:
    image: philter87/docker-workshop
    ports:
      - 9500:8080

