# You will need write this Dockerfile. We want the image to be based on the nginx docker image. 
# You can find it here: https://hub.docker.com/_/nginx
# The second code snippet on the link above, gives an example on how to create a simple Dockerfile. You should use the static frontend files 
# located in the folder 'frontend-radar/dist'

# 