# You will need write this Dockerfile. We want the image to be based on the nginx docker image. 
# You can find it here: https://hub.docker.com/_/nginx
# The second code snippet gives an example on how to create a simple Dockerfile. The static frontend files 
# are located in the folder 'frontend-radar/dist'