version: '3.1'
services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./jenkins_home:/var/jenkins_home
        ports:
            - "10000:8080"